name: coverage-test
on:
    push:

jobs:
    build:
        name: coverage-test
        runs-on: ubuntu-22.04
        steps:
            - name: Fetch repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
                submodules: recursive

            - name: Install packages
              run: sudo apt-get install build-essential libhdf5-dev hdf5-tools lcov

            - name: Build and run unittests
              run: ci/coverage_test.sh

            - name: Upload Coverage to Coveralls
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                path-to-lcov: build-coverage/coverage.info.cleaned
